maction_set_pref added

diff --git a/qubes-terminal-hotkeys b/qubes-terminal-hotkeys
--- a/qubes-terminal-hotkeys
+++ b/qubes-terminal-hotkeys
@@ -425,7 +425,7 @@ local ret=0
 
 if [[ "$1" == "$DOM_ZERO_ID" ]] ; then
 	#maybe TODO: go to sleep/hibernate
-	>&2 echo "WARNING: Dom0 puasing currently not implemented. Ignoring..."
+	>&2 echo "WARNING: Pausing dom0 is currently not implemented. Ignoring..."
 	shift
 	ret=1
 fi
@@ -435,6 +435,32 @@ if [ $# -gt 0 ] ; then
 	qvm-pause "$@"
 	ret=$?
 fi
+
+return $ret
+}
+
+#maction_set_pref [preference] [value] [vm 1] ... [vm n]
+#Set the given preference for the given VMs via `qvm-prefs`.
+#[preference]: The preference to set, e.g. `netvm` or `audiovm`. Has to be set statically in the `qubes-terminal-hotkeys` configuration.
+#[value]: The value to set the preference to. Has to be set statically in the `qubes-terminal-hotkeys` configuration. Use `--default` to reset the preference to its default value.
+function maction_set_pref {
+local pref="$1"
+local val="$2"
+local ret=0
+local vm=
+
+[ $# -lt 3 ] && errorOut "maction_set_pref: Not enough arguments! Maybe you forgot to statically set [preference] and [value] in your configuration?"
+shift 2
+
+for vm in "$@" ; do
+	[ $VERBOSE -eq 0 ] && printf 'Executing "qvm-prefs %q %q %q" ... ' "$vm" "$pref" "$val"
+	if qvm-prefs "$vm" "$pref" "$val" ; then
+		[ $VERBOSE -eq 0 ] && echo "Success."
+	else
+		[ $VERBOSE -eq 0 ] && echo "Failed."
+		ret=1
+	fi
+done
 
 return $ret
 }
